---
# =======
# - name: "install reqs on {{ ansible_hostname }}"
#   package:
#     name: ['openssh-server', 'rsync']
#     state: present 

- name: "Upgrading  npm "
  become: true
  shell: "npm install -g npm@latest"

# - name: copy backend files to ec2 instance
#   unarchive:
#     src: /root/project/
#   synchronize:
#     src: /root/project/backend/dist
#     dest: ./udapeople
#   ignore_errors: true

- name: Build backend
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: Stop and delete already running server
  ignore_errors: yes
  shell: |
    pm2 stop backend
    pm2 delete backend

- name: starting server
  become: true 
  shell: "cd /home/ubuntu ; pm2 start npm --name backend -- start"


