---
- name: copy backend files to ec2 instance
  unarchive:
    src: backend.tgz
    dest: /home/ubuntu/

- name: flat the wings and go home
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    npm install
    npm run build
    pm2 start npm --name backend -- start

- name: Moving on
  debug:
    msg: "We are done here for now.."