---
# =======
# - name: "install reqs on {{ ansible_hostname }}"
#   package:
#     name: ['openssh-server', 'rsync']
#     state: present 
- name: copy backend files to ec2 instance
  unarchive:
    src: backend.tgz
    dest: /home/ubuntu/


- name: "Upgrading  npm "
  become: true
  shell: "cd /home/ubuntu; npm install -g npm@latest"



- name: Build backend
  ignore_errors: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build

# - name: Stop and delete already running server
#   ignore_errors: yes
#   shell: |
#     pm2 stop backend
#     pm2 delete backend

- name: starting server
  become: true 
  shell: "cd /home/ubuntu ; pm2 start npm --name backend -- start"

- name: Moving on
  debug:
    msg: "We are done here for now.."
