---
- name: copy backend files to ec2 instance
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: flat the wings and go home
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@latest
    npm install
    npm run build
    pm2 start npm --name backend -- start
  ignore_errors: yes
  changed_when: False
  

- name: Moving on
  debug:
    msg: "We are done here for now.."