---

- name: copy backend files to ec2 instance
  copy:
    src: /root/project/backend.tgz
    dest: /home/ubuntu/backend.tgz

- name: extracting files
  unarchive:
    src: /home/ubuntu/backend.tgz
    dest: /home/ubuntu/

- name: "install npm on {{ ansible_hostname }}"
  shell: npm install 

- name: 'stop pm2'
  shell: pm2 stop default


- name: starting server
  become: true 
  shell: "cd /home/ubuntu ; pm2 start npm --name backend -- start"