version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@3.1
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflowid:
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws s3 rm s3://UdaPeople-${CIRCLE_WORKFLOW_ID:0:5} --recursive
            aws cloudformation delete-stack --stack-name UdaPeople-FE-${CIRCLE_WORKFLOW_ID:0:5}
            aws cloudformation delete-stack --stack-name UdaPeople-BE-${CIRCLE_WORKFLOW_ID:0:5}
